services:
  prom-server:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    network_mode: host

  grafana:
    image: grafana/grafana-oss
   
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prom-server  
    network_mode: host 

volumes:
  grafana-storage:
